apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: ashamchonak
spec:
  selector:
    app: tomcat-app
  type: ClusterIP
  ports:
  - name: tomcatsvcport
    port: 8080
    targetPort: tomcatport