apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-dep
  namespace: ashamchonak
  labels:
    app: tomcat-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-app-BUILD_NUMBER
  template:
    metadata:
      labels:
        app: tomcat-app-BUILD_NUMBER
    spec:
      containers:
      - name: tomcat
        image: "registry-ci.playpit.by/helloworld-ashamchonak:106"
        ports:
        - name: tomcatport
          containerPort: 8080
