apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  namespace: ymlechka
  labels:
    app: tomcat
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat
          image: "registry-ci.playpit.by/helloworld-ymlechka:552"
          ports:
            - name: tomcatport
              containerPort: 8080
#      imagePullSecrets:
#        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: ymlechka
spec:
  selector:
    app: tomcat
  type: LoadBalancer
  ports:
    - name: tomcatsvcport
      port: 8080
      targetPort: tomcatport
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tomcat-ingress
  namespace: ymlechka
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /helloworld-ws/$2
spec:
  rules:
    - host: ymlechka-app.k8s.playpit.by
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: tomcat-service
              servicePort: tomcatsvcport

