apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  namespace: kkaminski
  labels:
    app: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: "registry-ci.playpit.by/helloworld-kkaminski:47"
        ports:
        - name: tomcatport
          containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: kkaminski
spec:
  selector:
    app: tomcat
  type: ClusterIP
  ports:
  - name: tomcatsvcport
    port: 8080
    targetPort: tomcatport

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tomcat-ingress
  namespace: kkaminski
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - kkaminski-app.k8s.playpit.by
    secretName: letsencrypt-prod
  rules:
  - host: kkaminski-app.k8s.playpit.by
    http:
      paths:
      - path: /helloworld-ws
        backend:
          serviceName: tomcat-service
          servicePort: tomcatsvcport