---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld
  namespace: abutsko
  annotations:
    #nginx.ingress.kubernetes.io/app-root: /helloworld-ws
    nginx.ingress.kubernetes.io/rewrite-target: /helloworld-ws/$1
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    #nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    #nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - abutsko-app.k8s.playpit.by
    secretName: letsencrypt-prod
  rules:
  - host: abutsko-app.k8s.playpit.by
    http:
      paths:
      - path: /(.*)
        backend:
          serviceName: abutsko-helloworld
          servicePort: abutsko-svc
