- name: Deploying a new application version
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - block:
    - name: Deploying a sanity pod
      shell: |
        kubectl apply -f sanity.yml

    - name: Wait for port 8080 to become open
      wait_for:
        host: abutsko-sanity.abutsko.svc.cluster.local
        port: 8080
        delay: 10
        timeout: 80

    - name: Get old page
      uri:
        url: http://abutsko-helloworld.abutsko.svc.cluster.local:8080/helloworld-ws
        status_code: 200
        return_content: yes
      register: old_helloworld

    - name: Get new page
      uri:
        url: http://abutsko-sanity.abutsko.svc.cluster.local:8080/helloworld-ws
        status_code: 200
        return_content: yes
      register: new_helloworld

    - name: Testing new content
      fail:
        msg: It is the same content.
      when: new_helloworld.content == old_helloworld.content

  - block:
    - name: Change ingress to santy pod (for zero downtime)
      replace:
        path: ingress.yml
        regexp: abutsko-helloworld
        replace: abutsko-sanity

    - shell: cat ingress.yml
    
    - name: Change ingress to santy pod
      shell: |
        kubectl apply -f ingress.yml

    - name: Deploying a new deployment
      shell: |
        kubectl apply -f "{{ item }}"
      with_items:
      - deployment.yml
      - service.yml

    - name: Wait for port 8080 to become open
      wait_for:
        host: abutsko-helloworld.abutsko.svc.cluster.local
        port: 8080
        delay: 10
        timeout: 80

    - name: Return ingress
      replace:
        path: ingress.yml
        regexp: abutsko-sanity
        replace: abutsko-helloworld
    
    - name: Return ingress
      shell: |
        kubectl apply -f ingress.yml
